"""
Synthetic NCAA/Cape Cod amateur cohort generator.

This module builds a *simulation*, not a sample of real players. Every amateur player
is drawn from a latent ``talent`` parameter that drives two things at once:

1. the pitch-level tracking rows the pipeline sees as input, and
2. the player's "true" MLB outcome, stored in ``player_ground_truth``.

That makes the backtest a recovery test: given data generated by a known process, does
the normalize -> feature -> model pipeline recover the talent signal it was given? It is
deliberately *not* evidence that the model predicts real major-league performance --
no public dataset links amateur tracking data to major-league outcomes at the player
level, so no such claim is made anywhere in this project.

Environmental bias is injected as the exact inverse of the adjustment in
``src.normalization.environment``: raw metrics are divided by the altitude scalar and
scaled by the air-density ratio, so a correct adjustment recovers the latent value.
That is what makes the normalization layer measurable rather than decorative.
"""

from datetime import date, timedelta

import numpy as np
from sqlalchemy.orm import Session

from db.models import League, Player, PlayerGroundTruth, RawTrackingData, StadiumEnvironment
from src.config import get_settings
from src.logging_config import get_logger, log_filter_step
from src.normalization.environment import air_density_kg_m3

FIRST_NAMES = ["Alex", "Jordan", "Casey", "Riley", "Morgan", "Taylor", "Drew", "Quinn"]
LAST_NAMES = ["Smith", "Johnson", "Williams", "Brown", "Davis", "Miller", "Wilson", "Moore"]

SEED = 42
CONTEXT_YEAR = 2023

# Outcome model coefficients. These define the ground truth the pipeline must recover.
WOBA_INTERCEPT = 0.310
WOBA_PER_TALENT = 0.028
WOBA_PER_TIER = -0.020  # weaker competition (higher tier number) translates worse
WOBA_PER_AGE_YEAR = -0.006  # older player, same tools -> worse prospect
WOBA_NOISE_SD = 0.012

ERA_INTERCEPT = 4.30
ERA_PER_TALENT = -0.70  # lower ERA is better
ERA_PER_TIER = 0.25
ERA_PER_AGE_YEAR = 0.08
ERA_NOISE_SD = 0.30

STADIUMS = [
    ("NCAA", "Rosenblatt Field", 1100),
    ("NCAA", "Baum-Walker Stadium", 400),
    ("CCL", "Eldredge Park", 50),
    ("CCL", "Spillane Field", 30),
]


def _altitude_scalar(altitude_ft: float) -> float:
    """Same scalar ``adjust_velocity`` applies, so the seeder can invert it."""
    settings = get_settings()
    return 1.0 + settings.alpha * ((altitude_ft - settings.alt_std_ft) / 1000.0)


def _birth_date(rng: np.random.Generator) -> date:
    return date(int(rng.integers(1999, 2004)), int(rng.integers(1, 13)), int(rng.integers(1, 29)))


def _age_at(birth: date, year: int) -> int:
    age = year - birth.year
    if (birth.month, birth.day) > (7, 1):
        age -= 1
    return age


def _true_woba(talent: float, tier: int, age: int, rng: np.random.Generator) -> float:
    value = (
        WOBA_INTERCEPT
        + WOBA_PER_TALENT * talent
        + WOBA_PER_TIER * (tier - 4)
        + WOBA_PER_AGE_YEAR * (age - 21)
        + rng.normal(0, WOBA_NOISE_SD)
    )
    return float(np.clip(value, 0.200, 0.500))


def _true_era(talent: float, tier: int, age: int, rng: np.random.Generator) -> float:
    value = (
        ERA_INTERCEPT
        + ERA_PER_TALENT * talent
        + ERA_PER_TIER * (tier - 4)
        + ERA_PER_AGE_YEAR * (age - 21)
        + rng.normal(0, ERA_NOISE_SD)
    )
    return float(np.clip(value, 1.50, 9.00))


def _ensure_stadiums(session: Session, leagues: dict[str, League]) -> list[StadiumEnvironment]:
    """Create the four synthetic amateur parks once; reuse them on re-seed."""
    rng = np.random.default_rng(SEED + 1)
    stadiums = []
    for abbr, name, alt in STADIUMS:
        league = leagues[abbr]
        existing = (
            session.query(StadiumEnvironment)
            .filter_by(league_id=league.league_id, stadium_name=name)
            .first()
        )
        if existing:
            stadiums.append(existing)
            continue
        stadium = StadiumEnvironment(
            league_id=league.league_id,
            stadium_name=name,
            altitude=alt,
            park_factor_hr=float(rng.uniform(0.85, 1.15)),
            park_factor_obp=float(rng.uniform(0.90, 1.10)),
            temperature_mean=float(rng.uniform(18, 32)),
            humidity_mean=float(rng.uniform(35, 75)),
        )
        session.add(stadium)
        stadiums.append(stadium)
    session.flush()
    return stadiums


def seed_synthetic_data(session: Session, num_players: int = 50, lite: bool = False) -> dict:
    """
    Insert a synthetic amateur cohort plus its ground-truth outcomes.

    Deterministic: the same ``num_players`` and ``lite`` flag always produce the same
    cohort, so backtest numbers are reproducible across machines.
    """
    logger = get_logger()
    rng = np.random.default_rng(SEED)

    if lite:
        # Lite mode trims rows *per player*, not the cohort size: the models still need
        # enough distinct players to make a player-level train/validation split.
        num_players = min(num_players, 80)
        logger.info(f"synthetic_seed_lite num_players={num_players}")

    leagues = {league.abbreviation: league for league in session.query(League).all()}
    if "NCAA" not in leagues or "CCL" not in leagues:
        raise RuntimeError("Reference leagues NCAA and CCL must exist. Run: python main.py init-db")

    stadiums = _ensure_stadiums(session, leagues)
    stadium_env = {
        s.stadium_id: {
            "altitude": float(s.altitude),
            "scalar": _altitude_scalar(float(s.altitude)),
            "rho": air_density_kg_m3(float(s.temperature_mean), float(s.humidity_mean)),
        }
        for s in stadiums
    }
    rho_std = get_settings().rho_std

    tracking_count = 0
    ground_truth_count = 0

    for i in range(num_players):
        talent = float(rng.normal(0, 1))
        is_pitcher = i % 2 == 0
        birth = _birth_date(rng)
        age = _age_at(birth, CONTEXT_YEAR)

        player = Player(
            first_name=FIRST_NAMES[i % len(FIRST_NAMES)],
            last_name=f"{LAST_NAMES[i % len(LAST_NAMES)]}{i}",
            birth_date=birth,
            throws="L" if rng.random() < 0.28 else "R",
            bats=str(rng.choice(["L", "R", "S"], p=[0.35, 0.55, 0.10])),
            primary_position="P" if is_pitcher else str(rng.choice(["SS", "OF", "1B", "C"])),
        )
        session.add(player)
        session.flush()

        league = leagues["NCAA"] if i % 4 < 2 else leagues["CCL"]
        candidates = [s for s in stadiums if s.league_id == league.league_id]
        stadium = candidates[int(rng.integers(0, len(candidates)))]
        env = stadium_env[stadium.stadium_id]
        tier = league.competition_tier

        base_date = date(CONTEXT_YEAR, 3, 1) + timedelta(days=int(rng.integers(0, 120)))

        if is_pitcher:
            n_rows = int(rng.integers(12, 22)) if lite else int(rng.integers(80, 120))
            tracking_count += _emit_pitches(
                session, player, stadium, env, rho_std, talent, n_rows, base_date, rng
            )
            session.add(
                PlayerGroundTruth(
                    player_id=player.player_id,
                    role="pitcher",
                    latent_talent=round(talent, 4),
                    true_wOBA=None,
                    true_ERA=round(_true_era(talent, tier, age, rng), 2),
                    context_year=CONTEXT_YEAR,
                )
            )
        else:
            n_rows = int(rng.integers(10, 18)) if lite else int(rng.integers(30, 60))
            tracking_count += _emit_batted_balls(
                session, player, stadium, env, talent, n_rows, base_date, rng
            )
            session.add(
                PlayerGroundTruth(
                    player_id=player.player_id,
                    role="batter",
                    latent_talent=round(talent, 4),
                    true_wOBA=round(_true_woba(talent, tier, age, rng), 3),
                    true_ERA=None,
                    context_year=CONTEXT_YEAR,
                )
            )
        ground_truth_count += 1

    session.commit()
    log_filter_step("synthetic_tracking_insert", 0, tracking_count)
    logger.info(
        f"synthetic_seed_complete players={num_players} tracking_rows={tracking_count} "
        f"ground_truth_rows={ground_truth_count} stadiums={len(stadiums)}"
    )
    return {
        "players": num_players,
        "tracking_rows": tracking_count,
        "ground_truth_rows": ground_truth_count,
        "league_ids": {abbr: leagues[abbr].league_id for abbr in ("NCAA", "CCL")},
    }


def _emit_pitches(
    session: Session,
    player: Player,
    stadium: StadiumEnvironment,
    env: dict,
    rho_std: float,
    talent: float,
    n_rows: int,
    base_date: date,
    rng: np.random.Generator,
) -> int:
    """Pitch rows whose raw values carry park bias that normalization should remove."""
    latent_velo = 88.0 + 2.2 * talent
    latent_break = 16.0 + 2.0 * talent
    command_sd = float(np.clip(0.62 - 0.10 * talent, 0.28, 0.95))

    for j in range(n_rows):
        # Invert the adjustment model: raw = latent / scalar, so adj_velocity ~= latent.
        raw_velo = (latent_velo + rng.normal(0, 1.4)) / env["scalar"]
        # adjust_break multiplies by rho_std / rho_stadium, so pre-divide by that ratio.
        raw_break = (latent_break + rng.normal(0, 1.8)) * (env["rho"] / rho_std)

        session.add(
            RawTrackingData(
                player_id=player.player_id,
                stadium_id=stadium.stadium_id,
                game_date=base_date + timedelta(days=j % 30),
                context_year=CONTEXT_YEAR,
                pitch_type=str(rng.choice(["FF", "SL", "CH", "CU"])),
                release_speed=round(float(np.clip(raw_velo, 60, 105)), 1),
                spin_rate=int(np.clip(2050 + 240 * talent + rng.normal(0, 120), 900, 3400)),
                vertical_break=round(float(raw_break), 1),
                horizontal_break=round(float(rng.normal(-8, 3)), 1),
                vertical_approach_angle=round(float(rng.normal(-5.5, 1.2)), 2),
                extension=round(float(np.clip(6.0 + 0.28 * talent + rng.normal(0, 0.2), 3.1, 7.9)), 2),
                plate_x=round(float(rng.normal(0, command_sd)), 2),
                plate_z=round(float(rng.normal(2.5, command_sd * 0.8)), 2),
            )
        )
    return n_rows


def _emit_batted_balls(
    session: Session,
    player: Player,
    stadium: StadiumEnvironment,
    env: dict,
    talent: float,
    n_rows: int,
    base_date: date,
    rng: np.random.Generator,
) -> int:
    """Batted-ball rows; exit velocity carries the same invertible park bias."""
    latent_ev = 89.0 + 3.0 * talent
    sweet_spot_shift = 2.5 * talent
    chase_rate = float(np.clip(0.28 - 0.06 * talent, 0.05, 0.55))
    k_rate = float(np.clip(0.22 - 0.05 * talent, 0.03, 0.45))
    zone_sd = float(np.clip(0.55 - 0.08 * talent, 0.25, 0.90))

    for j in range(n_rows):
        raw_ev = (latent_ev + rng.normal(0, 4.0)) / env["scalar"]
        session.add(
            RawTrackingData(
                player_id=player.player_id,
                stadium_id=stadium.stadium_id,
                game_date=base_date + timedelta(days=j % 30),
                context_year=CONTEXT_YEAR,
                exit_velocity=round(float(np.clip(raw_ev, 35, 118)), 1),
                launch_angle=round(float(np.clip(rng.normal(15 + sweet_spot_shift, 11), -85, 85)), 1),
                hit_distance=int(np.clip(240 + 12 * talent + rng.normal(0, 60), 5, 545)),
                plate_x=round(float(rng.normal(0, zone_sd)), 2),
                plate_z=round(float(rng.normal(2.45, zone_sd * 0.8)), 2),
                is_strikeout=bool(rng.random() < k_rate),
                is_walk=bool(rng.random() < 0.08 + 0.03 * max(talent, 0)),
                is_chase=bool(rng.random() < chase_rate),
            )
        )
    return n_rows
